// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaoTK4kXOS8O0gpgXygrgk51lysXwYD-s',
    appId: '1:778789052441:web:8e1b3a9b599b359cd24a88',
    messagingSenderId: '778789052441',
    projectId: 'apps-9c32f',
    authDomain: 'apps-9c32f.firebaseapp.com',
    databaseURL: 'https://apps-9c32f.firebaseio.com',
    storageBucket: 'apps-9c32f.appspot.com',
    measurementId: 'G-ZGXREGCK81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6mvWDwFNIf0IzNyAfhB8R2xmeuCpoGDU',
    appId: '1:778789052441:android:17bff243daa44134d24a88',
    messagingSenderId: '778789052441',
    projectId: 'apps-9c32f',
    databaseURL: 'https://apps-9c32f.firebaseio.com',
    storageBucket: 'apps-9c32f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf5xgMrQQvk0-gxv6_JSpVcVK-9HY0BwA',
    appId: '1:778789052441:ios:981615be82c3df8bd24a88',
    messagingSenderId: '778789052441',
    projectId: 'apps-9c32f',
    databaseURL: 'https://apps-9c32f.firebaseio.com',
    storageBucket: 'apps-9c32f.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
